### ISSUE TITLE
Add diff between OpenJDK 8 to OpenJDK 9

### ISSUE THREAD

**Issue by jabrena** [AdoptOpenJDK/jdk-api-diff#1]
Good morning,

Maybe, it could be interesting to add the differences between `OpenJDK 8` to `OpenJDK 9`.
Many users continue using `OpenJDK 8` as the default `JVM`.

Another question, in September will appear `OpenJDK 11` and it will considered the next `LTS JDK`. Do you consider interesting to have a compassion from `OpenJDK 8` to `OpenJDK 11`?

Many thanks in advance, great repo.

Juan Antonio

**Comment by karianna** [comment]
IIRC This project isn't part of the AdoptOpenJDK build farm effort - but it would be interesting to see these results -> @gunnarmorling - would you be interested in setting up some jobs for us?

**Comment by gunnarmorling** [comment]
@karianna Yes, I can take a look. I'd need some pointers though on where to find the build farm, how to get an account there etc.

One general question is where to host the published reports; for the ones that exist already I'm using GH Pages with my personal fork of this project. It'd be nicer to enable GH Pages for the upstream repo here (couldn't do that due to lack of rights) or even somehow host them on adoptopenjdk.net. The latter would surely be nicer in terms of SEO etc.

In any case, I can take a look into manually creating reports from 8 to 9 and and 8 to 11 in the meantime.

**Comment by karianna** [comment]
@gunnarmorling You're already a member of the team so you have read access to ci.adoptopenjdk.net and can participate in any of the GH repos.  We co-ordinate all of our work on Slack so please sign up to: adoptopenjdk.net/slack.html and join the #build and #website channels in particular.  I'm happy for the GH pages to be hosted on this Org - what steps would need to be taken?  We can also look at merging them in with the website project (perhaps linking in the GH pages, not sure yet...).

Thank you!
